baseurl = "/"
languageCode = "en-GB"
title = "BADGE.TEAM documentation"
paginate = 5
theme = "hugo-theme-learn-badgeteam"

enableRobotsTXT = true
canonifyURLs = true

[Params]
  subtitle = ""
  description = "Documentation"
  powered_by = ""
  author = "BADGE.TEAM"
  copyright = ""
  date_format = "02-01-2006"
  showVisitedLinks = false
  disableInlineCopyToClipBoard = true
  themeVariant = "badgeteam"
  
[menu]
  [[menu.shortcuts]]
    name = "GIT repository"
    url = "https://github.com/badgeteam/ESP32-platform-firmware"
    weight = 0
  [[menu.shortcuts]]
    name = "Wiki"
    url = "https://wiki.badge.team"
    weight = 0
  [[menu.shortcuts]]
    name = "Hatchery"
    url = "https://badge.team"
    weight = 1

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true
